### ISSUE TITLE
Linear solving and matrix inverse should be more clever

### ISSUE THREAD

**Issue by fredrik-johansson** [fredrik-johansson/arb#205]
Gaussian elimination done directly in interval arithmetic gives poor enclosures for large matrices. An old paper that describes a few different methods that are easy to implement is Hansen & Smith, Interval Arithmetic in Matrix Computations, Part II, SIAM J. Numer. Anal., 4(1), 1–9. There are new papers that describe fancier techniques, but even the simple preconditioning trick (method 4) is a vast improvement. Example:

    from flint import *
    from mpmath import *

    n = 40
    A = randmatrix(n,n)
    B = randmatrix(n,1)
    AA = arb_mat(n, n, [arb(A[i//n,i%n], 1e-14) for i in range(n*n)])
    BB = arb_mat(n, 1, [arb(B[i,0], 1e-14) for i in range(n*1)])
    AI = inverse(A)   # approximate inverse with mpmath
    AAI = arb_mat(n, n, [AI[i//n,i%n] for i in range(n*n)])
    AA.solve(BB)   # naive interval solution
    (AAI*AA).solve(AAI*BB)   # preconditioned interval solution

The naive solution in one instance:

    [    [+/- 1.32e+5]]
    [    [+/- 6.04e+4]]
    [    [+/- 3.00e+4]]
    [    [+/- 4.58e+4]]
    [    [+/- 2.93e+4]]
    [    [+/- 2.09e+4]]
    [    [+/- 9.04e+3]]
    [    [+/- 2.93e+3]]
    [    [+/- 2.62e+3]]
    [    [+/- 1.93e+3]]
    [    [+/- 1.50e+3]]
    [    [+/- 8.99e+2]]
    [    [+/- 1.33e+3]]
    [    [+/- 6.14e+2]]
    [    [+/- 3.23e+2]]
    [    [+/- 3.24e+2]]
    [    [+/- 2.37e+2]]
    [    [+/- 1.49e+2]]
    [    [+/- 1.34e+2]]
    [       [+/- 91.3]]
    [       [+/- 70.9]]
    [       [+/- 11.8]]
    [       [+/- 12.3]]
    [       [+/- 24.4]]
    [       [+/- 9.99]]
    [       [+/- 7.60]]
    [       [+/- 11.4]]
    [       [+/- 3.73]]
    [       [+/- 1.89]]
    [       [+/- 3.64]]
    [       [+/- 1.50]]
    [       [+/- 2.56]]
    [       [+/- 1.24]]
    [      [+/- 0.732]]
    [      [+/- 0.447]]
    [      [+/- 0.896]]
    [ [0.5 +/- 0.0759]]
    [      [+/- 0.521]]
    [      [+/- 0.212]]
    [[-0.7 +/- 0.0472]]

The preconditioned solution:

    [ [0.02839853147 +/- 7.90e-12]]
    [ [-1.0500787426 +/- 4.48e-11]]
    [[-0.80417013789 +/- 2.33e-12]]
    [ [0.10241135449 +/- 6.26e-12]]
    [  [0.2737351746 +/- 2.11e-11]]
    [ [0.07527146134 +/- 5.56e-12]]
    [[-0.36775106771 +/- 6.79e-12]]
    [ [0.24625560798 +/- 2.87e-12]]
    [ [-0.4328648101 +/- 1.51e-11]]
    [  [0.1132582518 +/- 3.43e-11]]
    [  [0.6887292062 +/- 4.07e-11]]
    [ [0.33669069978 +/- 5.46e-12]]
    [ [0.38419150904 +/- 5.89e-12]]
    [[-0.19803441003 +/- 3.70e-12]]
    [[-0.06555745595 +/- 7.70e-12]]
    [  [0.2793057899 +/- 3.17e-11]]
    [[-0.22216454080 +/- 6.48e-12]]
    [[-0.94981852995 +/- 6.97e-12]]
    [[-0.44283327345 +/- 8.45e-12]]
    [ [-0.0066854861 +/- 6.38e-11]]
    [  [0.9304996076 +/- 4.09e-11]]
    [ [1.42913754750 +/- 8.34e-12]]
    [ [0.44546042722 +/- 6.36e-12]]
    [  [0.3450231038 +/- 4.13e-11]]
    [ [0.18352732449 +/- 5.73e-12]]
    [[-0.63541868806 +/- 4.49e-12]]
    [ [0.08467962923 +/- 3.24e-12]]
    [  [0.1062654616 +/- 5.91e-11]]
    [ [0.08812065325 +/- 5.94e-12]]
    [[-1.05566529972 +/- 9.66e-12]]
    [  [0.1417693049 +/- 4.45e-11]]
    [ [0.74041981272 +/- 8.82e-12]]
    [  [0.4540493110 +/- 9.64e-12]]
    [  [0.3964147231 +/- 4.49e-11]]
    [ [-0.1807095930 +/- 3.49e-11]]
    [[-0.67377800420 +/- 6.70e-12]]
    [ [0.50512672666 +/- 7.59e-12]]
    [  [0.4187979360 +/- 4.44e-11]]
    [  [0.1328337609 +/- 2.10e-11]]
    [[-0.72121349106 +/- 2.93e-12]]

The approximate solving could use doubles and even BLAS where available (with careful checking whether overflow or underflow is a problem).

Also, the preconditioned interval solution does not need to use interval Gaussian elimination; since one has almost the inverse of the identity matrix, it should be sufficient to compute some perturbation bounds in O(n^2) instead of O(n^3).

**Comment by thofma** [comment]
That would be awesome.

**Comment by arbguest** [comment]
I implemented this and tested it on the Hilbert matrix equation from Hansen and Smith. For n=5 prec=32 the preconditioning trick (method 4) yielded tighter bounds than interval Gaussian elimination (method 1) as expected, but n=10 prec=64 gave the opposite result. I'm not sure what to make of that, except that it makes me reluctant to submit a pull request.

**Comment by fredrik-johansson** [comment]
That's perhaps not surprising. Hilbert matrices are extremely ill-conditioned and in some sense realize the worst-case behavior of Gaussian elimination, so the pessimistic estimates of interval Gaussian elimination may not be too far off. The idea here is mainly to improve stability for well-conditioned matrices. But there could also be some bug in your code. Also two test cases both for rather small n are quite limited information, and I think a fair amount of systematic testing will be needed for this.

It would be nice if you could share your code for others to look at (I saw that you made a fork but couldn't see any commits there). I recommend discussing any code in this issue before making a pull request.

**Comment by arbguest** [comment]
> It would be nice if you could share your code for others to look at (I saw that you made a fork but couldn't see any commits there).

Here's a commit that uses the midpoint of interval Gaussian elimination as the `AAI` matrix.
https://github.com/arbguest/arb/commit/429365a175284ef4a28390bd89a4a5daa8dc13c0

**Comment by fredrik-johansson** [comment]
This is a good start.

The first solving should be done without ball operations. Otherwise we still have the problem that the bounds blow up forcing premature termination. So we need duplicated functions

arb_mat_approx_lu
arb_mat_approx_solve_lu_precomp
arb_mat_approx_solve

with basically the same code as arb_mat_lu, arb_mat_solve_lu_precomp, arb_mat_solve but with arf methods instead of arb methods and zeroing the radii in the end. (In the future these could be optimized.)

arb_mat_find_pivot_partial can be kept the same if the radii in the working matrix are kept zeroed, though I wonder if a different criterion than c != 0 for a viable pivot element should be used. Really one wants |c| < eps, but eps = 2^-prec is probably not good enough because it should depend on the magnitude of the entries in the matrix. I don't remember the correct theory here. Anyway, this is of secondary importance.

Then, as I said above, once we have the preconditioned system I think the second solving can be avoided. Since we have the system matrix (I + eps), it should be enough to verify ||eps|| < 1 and bound (eps + eps^2 + eps^3 + eps^4) using norms ...; but we might want both versions of the algorithm to compare.

Regarding names, I think the current arb_mat_solve (which you renamed _arb_mat_solve_hansen_method_1) should be renamed arb_mat_solve_lu, while _arb_mat_solve_hansen_method_4 should be renamed arb_mat_solve_precond. We'll also want an arb_mat_solve_precond_precomp that takes the precomputed matrices C and CA, I think.

Then, finally, arb_mat_solve should just be a wrapper for arb_mat_solve_lu and arb_mat_solve_precond depending on the size of the matrix and any other information that might be deemed relevant.

**Comment by arbguest** [comment]
Here's another commit, but no new tests or docs.
https://github.com/arbguest/arb/commit/e3e568fa5b427d562611b6756a73bee830d18f0c

**Comment by fredrik-johansson** [comment]
Thanks, this looks nice!

I will try some benchmarks in a short while.

This is more expensive than the first version of the algorithm. Besides the approximate LU factorization and 1 n x n multiplication, this now does 2 n x m multiplications and 2 approximate n x m back solves. This doesn't matter if m = 1, but it does matter if m = n, e.g. when computing a matrix inverse. I presume that this version of the algorithm is more accurate?

It might be reasonable to have the algorithm depend on the precision. Something like:

if p < Cn, use preconditioned solver optimized for accuracy
if Cn < p < Dn, use preconditioned solver optimized for speed
if p > Dn, use direct Gaussian elimination

for some well chosen C, D. In particular, for inverting a 1000 digit 10x10 matrix, we don't want to make the computation many times more expensive just to save 10 bits.

Another question is whether it would make sense to use higher internal precision for some of the computations, but that probably has to wait for a good benchmark suite.

**Comment by arbguest** [comment]
Your comment reminded me that the error bound should be specific to each column, so I've added a commit to change that. By the way, do you have name suggestions for the "preconditioning then interval gaussian elimination" vs. "approximate solving then bounding the error" methods?

**Comment by fredrik-johansson** [comment]
I don't know; it would be easier to tell once the code is in place.

The per-column code doesn't look correct to me (it doesn't sum over the entries and it doesn't reset err at each step of the main loop), but I may be misunderstanding what it's supposed to do.

What do you think of the simpler algorithm of computing the approximate inverse, multiplying both the system matrix and the right hand side by this inverse in ball arithmetic, and bounding the perturbation from the identity matrix (like my original example code)? Yes, computing the inverse explicitly is worse in some ways than using the LU factorization, but the matrix multiplication can (more easily) be optimized a lot more.

**Comment by arbguest** [comment]
Oops you're right, I've changed it so that it resets to zero for each column. The idea is that theorem 10.2 in that Rump paper is for a single column of the matrix, and it doesn't need to sum over entries of the column because it's taking the inf norm as suggested ("In particular, the ∞-norm is useful because it directly implies componentwise error bounds on the solution, and it is easy to calculate").

**Comment by arbguest** [comment]
> What do you think of the simpler algorithm of computing the approximate inverse, multiplying both the system matrix and the right hand side by this inverse in ball arithmetic, and bounding the perturbation from the identity matrix (like my original example code)?

I'll try adding this, with the idea that when E is small then `(I - E)^-1 V` = `(I + E + E^2 + E^3 + ...) V` = `V + bound((E + E^2 + E^3 + ...) V)` where `I - E` is `AAI*AA` and `V` is `AAI*BB`.

**Comment by arbguest** [comment]
Here are a couple more arb_mat_solve algorithms
https://github.com/fredrik-johansson/arb/commit/a947295ec9c97fc955241405bbf1465ccf9bc7bc
They have placeholder names arb_mat_solve_c and arb_mat_solve_d. The first one is like the python code in your original post, and the second one is similar but I've tried to 'bound the perturbation from the identity matrix' instead of doing the second gaussian elimination.

**Comment by fredrik-johansson** [comment]
Great! I'm running some benchmarks now.

**Comment by fredrik-johansson** [comment]
Quick benchmark program with output.

[sol.c.txt](https://github.com/fredrik-johansson/arb/files/1764663/sol.c.txt)

Testing:

Well-conditioned matrices, low precision
Well-conditioned matrices, high precision
Hilbert matrices, low precision
Hilbert matrices, high precision
Hilbert matrices, precision doubled until convergence

m = 1
m = n

Some observations:

1. solve_precond/c/d are roughly 3-5 times slower than solve_lu
2. solve_precond, solve_c and solve_d have virtually the same performance for n x 1 rhs
3. solve_d is about 1.5x faster than solve_precond for n x n rhs (solve_c is somewhere in between)
4. solve_c is slightly more accurate (just by a couple of bits in the well-conditioned case)
5. The difference in accuracy between solve_precond / solve_c and solve_d gets bigger in the ill-conditioned case when the precision loss with either method starts to become a significant fraction of the total precision; then solve_precond / solve_c will sometimes be much more accurate than solve_d.

For the main solve function, something like the following which I put in the benchmark code (alg == 4) could be used:

    int
    arb_mat_solve_choose(arb_mat_t X, const arb_mat_t A, const arb_mat_t B, slong prec)
    {
        slong n = arb_mat_nrows(A);
        slong m = arb_mat_ncols(B);

        if (n <= 4 || prec > 10.0 * n)
            return arb_mat_solve_lu(X, A, B, prec);
        else if (m < 0.1 * n + 1)
            return arb_mat_solve_c(X, A, B, prec);
        else
            return arb_mat_solve_d(X, A, B, prec);
    }

Here the idea is to stick to solve_lu if we only estimate losing say 10% of the precision (this guess is not completely accurate, but it's something).

It would be possible to put the second conditional inside solve_c/solve_d and merge them, to keep the number of methods down (although this would not give the user the choice between them).

The question is whether to keep your solve_precond (with Rump's version of the algorithm) as well. Although my tests showed no real advantage for this method, it could very well be superior for some other matrices. If someone else has some good idea for benchmark problems (the less artificial, the better), that could be useful.

Of course, the relative performances may change slightly with future tuning of the various building blocks (matrix multiplication, approximate solving). Already now, the timings will look a bit different if you use lots of threads, since this speeds up matrix multiplication but not Gaussian elimination.

For inverting Hilbert matrices by repeatedly doubling the precision the new algorithm will be 2-3 times slower than before. This seems unavoidable if we want to optimize for well-conditioned matrices. Also, nothing prevents the user from calling solve_lu explicitly in such a case.

We could actually do a bit better: we test if the pivot element is 0 in the approximate Gaussian elimination, but we could allow early termination if the pivot element is just very small, e.g. smaller than eps = 2^-(0.9*prec). This eps is not literally what should be used, because it doesn't account for scaling of the matrix. I think there is some standard theory here for estimating the condition number during the execution of Gaussian elimination, but I don't remember any details.

Some other minor comments about the code:

Some ints should be slongs.

There are some redundant matrix allocations, where one matrix could be recycled internally.

**Comment by fredrik-johansson** [comment]
Perhaps rename the algorithm based on Rump 10.2 -> solve_preapprox or something similar (because here the verification step takes a precomputed approximate solution).

**Comment by arbguest** [comment]
> The question is whether to keep your solve_precond (with Rump's version of the algorithm) as well. Although my tests showed no real advantage for this method

We can leave it out. My feeling is that one of its advantages is its flexibility to work with any approximate solution and any approximate inverse, whereas for the other algorithms these two guesses are tied together more complicatedly. Because we aren't using this flexibility, it might not be surprising that it's worse.

**Comment by fredrik-johansson** [comment]
> We can leave it out.

Actually, I think it could be useful to keep it in some form, especially if there is a version where the user provides the approximate solution. Namely, the user might compute an approximate solution with some external numerical code and pass it through here for certification.

**Comment by arbguest** [comment]
It could be possible to improve solve_d by using one more term in the power series. It would use like one extra matrix multiplication.

**Comment by fredrik-johansson** [comment]
I thought about that, but I'm not sure if it's worth it.

**Comment by fredrik-johansson** [comment]
@arbguest are you going to work more on this or do you want me to finish the code?

**Comment by arbguest** [comment]
I might work on it more, I think I was slow to do it because I wasn't looking forward to adding all the tests and documentation. Should the `arb_mat_approx_*` test code include exact equality checks of invariants like `midpoint(f(x)) == approx_f(x)`? I think this is possible because these algorithms don't make decisions based on the error radius if I remember correctly.

**Comment by fredrik-johansson** [comment]
> I might work on it more

Great.

> Should the arb_mat_approx_* test code include exact equality checks of invariants like midpoint(f(x)) == approx_f(x)? I think this is possible because these algorithms don't make decisions based on the error radius if I remember correctly.

This is not future-proof. In fact I think it's already going to fail due to divisions.

If it makes your life easier, I don't think the approx functions even need to be tested directly. It should be enough to check that the preconditioned solving works (with a copy of the t-solve code). If the approximate solving doesn't work correctly then this test ought to fail to converge.

**Comment by arbguest** [comment]
https://github.com/arbguest/arb/commit/03a2a201ee81e3427d8b180f4d0e2ae7b7f5af77

> Some ints should be slongs.

changed two `int i, j;` to `slong i, j`

> There are some redundant matrix allocations, where one matrix could be recycled internally.

removed three redundant matrix allocations

> For the main solve function, something like the following

pasted this as the new `arb_mat_solve`

> Perhaps rename the algorithm

renamed to solve_preapprox and moved it into its own file with its own test

**Comment by fredrik-johansson** [comment]
It looks like the main things left to do are renaming solve_c/solve_d -> solve_precond, moving solve_precond and solve_lu into separate files, and putting in the test code and documentation for each. As I said before, consider just merging solve_c and solve_d with the m < 0.1 * n + 1 condition for which method to use put into that function. (But if you want to make them two different versions, that's also fine.)

Put in correct copyright lines.

I would prefer not to add the arb_mat_submul function. The loop will be slower than an arb_mat_mul when the latter is optimized (already now with >1 threads), and as a wrapper for arb_mat_mul, it will just add a mandatory temporary allocation that sometimes can be avoided when doing a manual mul + sub by reusing matrices. It would be reasonable to add fused operations when optimizing matrix multiplication in the future but I don't think this is the right time.

Come to think of it, a better name for arb_mat_solve_preapprox might be arb_mat_validate_solution. However, it does require more inputs than just the approximate solution... so perhaps just leave it as is.

**Comment by fredrik-johansson** [comment]
With that done, it looks like it should be ready for merging.

Future items:

* Implement the same algorithms for acb_mat.
* Implement the Hansen & Smith determinant algorithm

**Comment by arbguest** [comment]
I've made a pull request for this issue https://github.com/fredrik-johansson/arb/pull/216
